version: '2'
services:
  test:
    image: behave
    #command: behave
    network_mode: "host"
    shm_size: 256m
    environment:
      - DISPLAY=$DISPLAY
      - CHROME_BINARY_PATH=/usr/bin/google-chrome
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - ./app/:/behave 
  backend:
    image: $IMAGE_DEPLOY
    ports:
      - 81:3000    
    container_name: $PROJECT_NAME
    volumes:
      - ./app/:/app
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LC_ALL: en_US.UTF-8
    command: yarn start 
  mysql:
      image: mysql:5.5
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: reservation
      ports:
        - 3307:3306
      volumes:
        - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      command: mysqld --sql_mode=""
